version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"  # Using environment variable for the port
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"  # Using environment variable for the port
